version: "3"
services:
  server:
    build: ./backend
    ports:
      - "80:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/user/src/app
    depends_on:
      - server
